import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
//
type ExploreData = {
  img: string;
  location: string;
  distance: string;
};
type AnywhereData = {
  img: string;
  title: string;
};

export default function Home({
  exploreData,
  anywhereData,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  // const exploreData = props.children;
  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData.map((explore, idx) => (
              <SmallCard
                key={idx}
                img={explore.img}
                distance={explore.distance}
                location={explore.location}
              />
              // <div key={idx}>{explore.location}</div>
            ))}
          </div>
        </section>
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3">
            {anywhereData.map((anywhere, idx) => (
              <MediumCard key={idx} img={anywhere.img} title={anywhere.title} />
            ))}
          </div>
        </section>

        <section className="relative py-16 cursor-pointer">
          <LargeCard
            img={"https://links.papareact.com/4cj"}
            title="The Greatest Outdoors"
            description="Wishlists curated by Airbnb."
            buttonText="Get Inspired"
          />
        </section>
      </main>
    </div>
  );
}
export const getStaticProps: GetStaticProps<{
  exploreData: ExploreData[];
  anywhereData: AnywhereData[];
}> = async () => {
  // use appropriate error handling
  let exploreData;
  let anywhereData;
  try {
    const res = await fetch("https://www.jsonkeeper.com/b/4G1G");
    exploreData = await res.json();
  } catch (e) {
    console.log(e);
  }

  try {
    const res = await fetch("https://www.jsonkeeper.com/b/VHHT");
    anywhereData = await res.json();
  } catch (e) {
    console.log(e);
  }
  // Sending fetched data to the page component via props.
  return {
    props: {
      exploreData,
      anywhereData,
    },
  };
};
